export const EXTENSION_TRIGGER_AUTHENTICATION = 'wallet:authentication'
export const EXTENSION_TRIGGER_AUTHENTICATED = 'wallet:authenticated'
export const EXTENSION_TRIGGER_UNAUTHENTICATED = 'wallet:unauthenticated'
export const EXTENSION_TRIGGER_INIT_SENSETIVE = 'wallet:init-sensetive'
export const EXTENSION_TRIGGER_ADD_CREDENTIAL = 'wallet:add-credential'
export const EXTENSION_TRIGGER_REMOVE_CREDENTIAL = 'wallet:remove-credential'
export const EXTENSION_TRIGGER_DEFAULT_SIGNATURE = 'signer:default-signature'
export const EXTENSION_TRIGGER_INCOMMING_DOC_RECEIVED = 'documnet:received'
export const EXTENSION_TRIGGER_RETRIEVE_NAME = 'credentail:get-name'
export const EXTENSION_TRIGGER_PRODUCE_IDENTITY = 'identity:produce'


export const META_ROLE_CREDENTIAL = 'credential'
export const META_ROLE_CLAIM = 'claim'
export const META_ROLE_OFFER = 'offer'
export const META_ROLE_REQUEST = 'request'
export const META_ROLE_RESPONSE = 'response'
export const META_ROLE_REFUSE = 'refuse'